version: '2'
services:
  app:
    build: .
    environment:
      DATABASE_URL: mysql://root:pass@mysql:3306
      MYSQL_ROOT_URL: 'pass'
    # command: python app.py
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/mappin_server
    links:
      - mysql
  mysql:
    image: mysql:5.7.10
    command: bash -c 'usermod -o -u 1000 mysql; groupmod -o -g 500 mysql; chown -R mysql:root /var/run/mysqld/; /entrypoint.sh mysqld --user=mysql --console'
    
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local

