"""empty message

Revision ID: 0bb791801a96
Revises: 
Create Date: 2017-10-11 09:34:28.786970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb791801a96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('name_kana', sa.Unicode(length=255), nullable=False),
    sa.Column('location', sa.Unicode(length=255), nullable=False),
    sa.Column('location_kana', sa.Unicode(length=255), nullable=False),
    sa.Column('responsible_person', sa.Unicode(length=255), nullable=False),
    sa.Column('responsible_person_kana', sa.Unicode(length=255), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('phone_number', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companyacounts',
    sa.Column('login_id', sa.Unicode(length=255), nullable=False),
    sa.Column('login_password', sa.Unicode(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('login_id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('url', sa.Unicode(length=255), nullable=True),
    sa.Column('latitude', sa.Unicode(length=255), nullable=True),
    sa.Column('longitude', sa.Unicode(length=255), nullable=True),
    sa.Column('area_radius', sa.Unicode(length=255), nullable=True),
    sa.Column('installation_datetime', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('companyacounts')
    op.drop_table('companies')
    # ### end Alembic commands ###
